server:
  port: 8084
  servlet:
    context-path: /springboot_drools
spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver #todo 旧版驱动
      username: root
      password: root
      url: jdbc:mysql:///test?serverTimezone=UTC&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
      type: com.alibaba.druid.pool.DruidDataSource
      #配置初始化大小/最小/最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      #获取连接等待超时时间
      maxWait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybaits-plus日志
  global-config:
    db-config:
      logic-delete-value: 1 #逻辑删除配置
      logic-not-delete-value: 0
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.drools.pojo
